
import 'package:circleciguvi/productdisplay/rating_model.dart';


import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'rating_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'rating_model.g.dart';

@freezed
abstract class RatingModel with _$RatingModel{
  const factory RatingModel({
    required num rate,
    required int count,
  }) = _RatingModel;

  factory RatingModel.fromJson(Map<String, Object?> json) => _$RatingModelFromJson(json);
}

